# Site settings
title: Insecta.Farm
email: insectafarm@biology.bio.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://insectafarm.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: insectafarm

# Build settings
markdown: kramdown
